const CommonTypes = {
    SET_APP_LOADER: "COMMON_TYPES.SET_APP_LOADER",

    /* LOCATION */
    SET_LOCATION:"COMMON_TYPES.SET_LOCATION",
    RESET_LOCATION:"COMMON_TYPES.RESET_LOCATION",

    SHIPPING_ADDRESS_LIST_INPROGRESS:"COMMON_TYPES.SHIPPING_ADDRESS_LIST_INPROGRESS",
    SHIPPING_ADDRESS_LIST_SUCCESS:"COMMON_TYPES.SHIPPING_ADDRESS_LIST_SUCCESS",
    SHIPPING_ADDRESS_LIST_ERROR:"COMMON_TYPES.SHIPPING_ADDRESS_LIST_ERROR",

    BILLING_ADDRESS_LIST_INPROGRESS:"COMMON_TYPES.BILLING_ADDRESS_LIST_INPROGRESS",
    BILLING_ADDRESS_LIST_SUCCESS:"COMMON_TYPES.BILLING_ADDRESS_LIST_SUCCESS",
    BILLING_ADDRESS_LIST_ERROR:"COMMON_TYPES.BILLING_ADDRESS_LIST_ERROR"

}

export default CommonTypes;