export const WASTAGESCRUB_CREATE = "WASTAGESCRUB_CREATE";
export const WASTAGESCRUB_UPDATE = "WASTAGESCRUB_UPDATE";
export const WASTAGESCRUB_FETCH = "WASTAGESCRUB_FETCH";
export const WASTAGESCRUB_SUCCESS = "WASTAGESCRUB_SUCCESS";
export const WASTAGESCRUB_FAILURE = "WASTAGESCRUB_FAILURE";
export const WASTAGESCRUB_DELETE = "WASTAGESCRUB_DELETE";
