export const INVENTORYMASTER_CREATE = "INVENTORYMASTER_CREATE";
export const INVENTORYMASTER_UPDATE = "INVENTORYMASTER_UPDATE";
export const INVENTORYMASTER_FETCH = "INVENTORYMASTER_FETCH";
export const INVENTORYMASTER_SUCCESS = "INVENTORYMASTER_SUCCESS";
export const INVENTORYMASTER_FAILURE = "INVENTORYMASTER_FAILURE";
export const INVENTORYMASTER_DELETE = "INVENTORYMASTER_DELETE";
