const TaskTypes ={
    GET_TASK_LIST_PROGRESS: "TASK_TYPE.GET_TASK_LIST_PROGRESS",
    GET_TASK_LIST_SUCCESS: "TASK_TYPE.GET_TASK_LIST_SUCCESS",
    GET_TASK_LIST_ERROR: "TASK_TYPE.GET_TASK_LIST_ERROR",

    GET_MY_TASK_LIST_PROGRESS: "TASK_TYPE.GET_MY_TASK_LIST_PROGRESS",
    GET_MY_TASK_LIST_SUCCESS: "TASK_TYPE.GET_MY_TASK_LIST_SUCCESS",
    GET_MY_TASK_LIST_ERROR: "TASK_TYPE.GET_MY_TASK_LIST_ERROR",

}

export default TaskTypes;