const PurchaseTypes ={
    CREATE_PURCHASE_ORDER_PROGRESS:"PURCHASE_TYPE.CREATE_PURCHASE_ORDER_PROGRESS",
    CREATE_PURCHASE_ORDER_SUCCESS:"PURCHASE_TYPE.CREATE_PURCHASE_ORDER_SUCCESS",
    CREATE_PURCHASE_ORDER_ERROR:"PURCHASE_TYPE.CREATE_PURCHASE_ORDER_ERROR",
    CREATE_PURCHASE_ORDER_RESET:"PURCHASE_TYPE.CREATE_PURCHASE_ORDER_RESET",

    GET_PURCHASE_ORDER_PROGRESS:"PURCHASE_TYPE.GET_PURCHASE_ORDER_PROGRESS",
    GET_PURCHASE_ORDER_SUCCESS:"PURCHASE_TYPE.GET_PURCHASE_ORDER_SUCCESS",
    GET_PURCHASE_ORDER_ERROR:"PURCHASE_TYPE.GET_PURCHASE_ORDER_ERROR",

    UPDATE_PURCHASE_ORDER_PROGRESS:"PURCHASE_TYPE.UPDATE_PURCHASE_ORDER_PROGRESS",
    UPDATE_PURCHASE_ORDER_SUCCESS:"PURCHASE_TYPE.UPDATE_PURCHASE_ORDER_SUCCESS",
    UPDATE_PURCHASE_ORDER_ERROR:"PURCHASE_TYPE.UPDATE_PURCHASE_ORDER_ERROR",
    UPDATE_PURCHASE_ORDER_RESET:"PURCHASE_TYPE.UPDATE_PURCHASE_ORDER_RESET",

}
export default PurchaseTypes