const CustomerTypes ={
    GET_CUSTOMER_LIST_PROGRESS: "CUSTOMER_TYPE.GET_CUSTOMER_LIST_PROGRESS",
    GET_CUSTOMER_LIST_SUCCESS: "CUSTOMER_TYPE.GET_CUSTOMER_LIST_SUCCESS",
    GET_CUSTOMER_LIST_ERROR: "CUSTOMER_TYPE.GET_CUSTOMER_LIST_ERROR",
    SET_CUSTOMER_LIST: "CUSTOMER_TYPE.SET_CUSTOMER_LIST",

    SET_CUSTOMER_DETAIL_PROGRESS: "CUSTOMER_TYPE.SET_CUSTOMER_DETAIL_PROGRESS",
    SET_CUSTOMER_DETAIL_SUCCESS: "CUSTOMER_TYPE.SET_CUSTOMER_DETAIL_SUCCESS",
    SET_CUSTOMER_DETAIL_ERROR: "CUSTOMER_TYPE.SET_CUSTOMER_DETAIL_ERROR",
    RESET_CUSTOMER_DETAIL: "CUSTOMER_TYPE.RESET_CUSTOMER_DETAIL",
  
    GET_TASK_LIST_PROGRESS: "CUSTOMER_TYPE.GET_TASK_LIST_PROGRESS",
    GET_TASK_LIST_SUCCESS: "CUSTOMER_TYPE.GET_TASK_LIST_SUCCESS",
    GET_TASK_LIST_ERROR: "CUSTOMER_TYPE.GET_TASK_LIST_ERROR",

    GET_MYTASK_LIST_PROGRESS: "CUSTOMER_TYPE.GET_MYTASK_LIST_PROGRESS",
    GET_MYTASK_LIST_SUCCESS: "CUSTOMER_TYPE.GET_MYTASK_LIST_SUCCESS",
    GET_MYTASK_LIST_ERROR: "CUSTOMER_TYPE.GET_MYTASK_LIST_ERROR",
}
export default CustomerTypes
