const MaterialSubCatTypes ={
    CREATE_MAT_SUBCATEGORY_PROGRESS:"MAT_CAT_TYPE.CREATE_MAT_SUBCATEGORY_PROGRESS",
    CREATE_MAT_SUBCATEGORY_SUCCESS:"MAT_CAT_TYPE.CREATE_MAT_SUBCATEGORY_SUCCESS",
    CREATE_MAT_SUBCATEGORY_ERROR:"MAT_CAT_TYPE.CREATE_MAT_SUBCATEGORY_ERROR",
    CREATE_MAT_SUBCATEGORY_RESET:"MAT_CAT_TYPE.CREATE_MAT_SUBCATEGORY_RESET",

    GET_MAT_SUBCATEGORY_PROGRESS:"MAT_CAT_TYPE.GET_MAT_SUBCATEGORY_PROGRESS",
    GET_MAT_SUBCATEGORY_SUCCESS:"MAT_CAT_TYPE.GET_MAT_SUBCATEGORY_SUCCESS",
    GET_MAT_SUBCATEGORY_ERROR:"MAT_CAT_TYPE.GET_MAT_SUBCATEGORY_ERROR",

    UPDATE_MAT_SUBCATEGORY_PROGRESS:"MAT_CAT_TYPE.UPDATE_MAT_SUBCATEGORY_PROGRESS",
    UPDATE_MAT_SUBCATEGORY_SUCCESS:"MAT_CAT_TYPE.UPDATE_MAT_SUBCATEGORY_SUCCESS",
    UPDATE_MAT_SUBCATEGORY_ERROR:"MAT_CAT_TYPE.UPDATE_MAT_SUBCATEGORY_ERROR",
    UPDATE_MAT_SUBCATEGORY_RESET:"MAT_CAT_TYPE.UPDATE_MAT_SUBCATEGORY_RESET",

}
export default MaterialSubCatTypes