const LeadTypes = {
  CREATE_LEAD_PROGRESS: "LEAD_TYPE.CREATE_LEAD_PROGRESS",
  CREATE_LEAD_SUCCESS: "LEAD_TYPE.CREATE_LEAD_SUCCESS",
  CREATE_LEAD_ERROR: "LEAD_TYPE.CREATE_LEAD_ERROR",
  CREATE_LEAD_RESET: "LeadTypes.CREATE_LEAD_RESET",

  GET_LEAD_LIST_PROGRESS: "LEAD_TYPE.GET_LEAD_LIST_PROGRESS",
  GET_LEAD_LIST_SUCCESS: "LEAD_TYPE.GET_LEAD_LIST_SUCCESS",
  GET_LEAD_LIST_ERROR: "LEAD_TYPE.GET_LEAD_LIST_ERROR",
  SET_LEAD_LIST: "LEAD_TYPE.SET_LEAD_LIST",

  SET_LEAD_UPDATE_PROGRESS: "LEAD_TYPE.SET_LEAD_UPDATE_PROGRESS",
  SET_LEAD_UPDATE_SUCCESS: "LEAD_TYPE.SET_LEAD_UPDATE_SUCCESS",
  SET_LEAD_UPDATE_ERROR: "LEAD_TYPE.SET_LEAD_UPDATE_ERROR",

  SET_LEAD_DETAIL_PROGRESS: "LEAD_TYPE.SET_LEAD_DETAIL_PROGRESS",
  SET_LEAD_DETAIL_SUCCESS: "LEAD_TYPE.SET_LEAD_DETAIL_SUCCESS",
  SET_LEAD_DETAIL_ERROR: "LEAD_TYPE.SET_LEAD_DETAIL_ERROR",
  RESET_LEAD_DETAIL: "LEAD_TYPE.RESET_LEAD_DETAIL",

  DELETE_LEAD_PROGRESS: "LEAD_TYPE.DELETE_LEAD_PROGRESS",
  DELETE_LEAD_SUCCESS: "LEAD_TYPE.DELETE_LEAD_SUCCESS",
  DELETE_LEAD_ERROR: "LEAD_TYPE.DELETE_LEAD_ERROR",

  GET_LEAD_STAGE_PROGRESS: "LEAD_TYPE.GET_LEAD_STAGE_PROGRESS",
  GET_LEAD_STAGE_SUCCESS: "LEAD_TYPE.GET_LEAD_STAGE_SUCCESS",
  GET_LEAD_STAGE_ERROR: "LEAD_TYPE.GET_LEAD_STAGE_ERROR",

  GET_LEAD_SOURCE_PROGRESS: "LEAD_TYPE.GET_LEAD_SOURCE_PROGRESS",
  GET_LEAD_SOURCE_SUCCESS: "LEAD_TYPE.GET_LEAD_SOURCE_SUCCESS",
  GET_LEAD_SOURCE_ERROR: "LEAD_TYPE.GET_LEAD_SOURCE_ERROR",

  CREATE_LEAD_ACTIVITY_INPROGRESS: "LEAD_TYPE.CREATE_LEAD_ACTIVITY_INPROGRESS",
  CREATE_LEAD_ACTIVITY_SUCCESS: "LEAD_TYPE.CREATE_LEAD_ACTIVITY_SUCCESS",
  CREATE_LEAD_ACTIVITY_ERROR: "LEAD_TYPE.CREATE_LEAD_ACTIVITY_ERROR",

  LEAD_CONTACT_VERIFY_INPROGRESS:"LEAD_TYPE.LEAD_CONTACT_VERIFY_INPROGRESS",
  LEAD_CONTACT_VERIFY_SUCCESS:"LEAD_TYPE.LEAD_CONTACT_VERIFY_SUCCESS",
  LEAD_CONTACT_VERIFY_ERROR:"LEAD_TYPE.LEAD_CONTACT_VERIFY_ERROR",
};

export default LeadTypes;
