const AuthTypes ={
    LOGIN_IN_PROGRESS: "AUTH_TYPE.LOGIN_IN_PROGRESS",
    LOGIN_IN_SUCCESS: "AUTH_TYPES.LOGIN_IN_SUCCESS",
    LOGIN_IN_ERROR: "AUTH_TYPES.LOGIN_IN_ERROR",

    FORGOT_PASSWORD_PROGRESS: "AUTH_TYPES.FORGOT_PASSWORD_PROGRESS",
    FORGOT_PASSWORD_SUCCESS: "AUTH_TYPES.FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_ERROR: "AUTH_TYPES.FORGOT_PASSWORD_ERROR",
    RESET_FORGOT_PASSWORD: "AUTH_TYPES.RESET_FORGOT_PASSWORD",

}

export default AuthTypes;
