export const STOCKENTRY_CREATE = "STOCKENTRY_CREATE";
export const STOCKENTRY_UPDATE = "STOCKENTRY_UPDATE";
export const STOCKENTRY_FETCH = "STOCKENTRY_FETCH";
export const STOCKENTRY_SUCCESS = "STOCKENTRY_SUCCESS";
export const STOCKENTRY_FAILURE = "STOCKENTRY_FAILURE";
export const STOCKENTRY_DELETE = "STOCKENTRY_DELETE";
