export const MATERIALTRANSFER_CREATE = "MATERIALTRANSFER_CREATE";
export const MATERIALTRANSFER_UPDATE = "MATERIALTRANSFER_UPDATE";
export const MATERIALTRANSFER_FETCH = "MATERIALTRANSFER_FETCH";
export const MATERIALTRANSFER_SUCCESS = "MATERIALTRANSFER_SUCCESS";
export const MATERIALTRANSFER_FAILURE = "MATERIALTRANSFER_FAILURE";
// export const MATERIALTRANSFER_DELETE = "MATERIALTRANSFER_DELETE";
