const MaterialItemTypes ={
    CREATE_MAT_ITEM_PROGRESS:"MAT_CAT_TYPE.CREATE_MAT_ITEM_PROGRESS",
    CREATE_MAT_ITEM_SUCCESS:"MAT_CAT_TYPE.CREATE_MAT_ITEM_SUCCESS",
    CREATE_MAT_ITEM_ERROR:"MAT_CAT_TYPE.CREATE_MAT_ITEM_ERROR",
    CREATE_MAT_ITEM_RESET:"MAT_CAT_TYPE.CREATE_MAT_ITEM_RESET",

    GET_MAT_ITEM_PROGRESS:"MAT_CAT_TYPE.GET_MAT_ITEM_PROGRESS",
    GET_MAT_ITEM_SUCCESS:"MAT_CAT_TYPE.GET_MAT_ITEM_SUCCESS",
    GET_MAT_ITEM_ERROR:"MAT_CAT_TYPE.GET_MAT_ITEM_ERROR",

    UPDATE_MAT_ITEM_PROGRESS:"MAT_CAT_TYPE.UPDATE_MAT_ITEM_PROGRESS",
    UPDATE_MAT_ITEM_SUCCESS:"MAT_CAT_TYPE.UPDATE_MAT_ITEM_SUCCESS",
    UPDATE_MAT_ITEM_ERROR:"MAT_CAT_TYPE.UPDATE_MAT_ITEM_ERROR",
    UPDATE_MAT_ITEM_RESET:"MAT_CAT_TYPE.UPDATE_MAT_ITEM_RESET",

}
export default MaterialItemTypes