export const ACTIVITYQUERY_CREATE = "ACTIVITYQUERY_CREATE";
export const ACTIVITYQUERY_UPDATE = "ACTIVITYQUERY_UPDATE";
export const ACTIVITYQUERY_FETCH = "ACTIVITYQUERY_FETCH";
export const ACTIVITYQUERY_SUCCESS = "ACTIVITYQUERY_SUCCESS";
export const ACTIVITYQUERY_FAILURE = "ACTIVITYQUERY_FAILURE";
export const ACTIVITYQUERY_DELETE = "ACTIVITYQUERY_DELETE";
export const ACTIVITYQUERYQUESTION_FETCH = "ACTIVITYQUERYQUESTION_FETCH";
export const ACTIVITYQUERY_ADD = "ACTIVITYQUERY_ADD";



