const MaterialCatTypes ={
    CREATE_MAT_CATEGORY_PROGRESS:"MAT_CAT_TYPE.CREATE_MAT_CATEGORY_PROGRESS",
    CREATE_MAT_CATEGORY_SUCCESS:"MAT_CAT_TYPE.CREATE_MAT_CATEGORY_SUCCESS",
    CREATE_MAT_CATEGORY_ERROR:"MAT_CAT_TYPE.CREATE_MAT_CATEGORY_ERROR",
    CREATE_MAT_CATEGORY_RESET:"MAT_CAT_TYPE.CREATE_MAT_CATEGORY_RESET",

    GET_MAT_CATEGORY_PROGRESS:"MAT_CAT_TYPE.GET_MAT_CATEGORY_PROGRESS",
    GET_MAT_CATEGORY_SUCCESS:"MAT_CAT_TYPE.GET_MAT_CATEGORY_SUCCESS",
    GET_MAT_CATEGORY_ERROR:"MAT_CAT_TYPE.GET_MAT_CATEGORY_ERROR",

    UPDATE_MAT_CATEGORY_PROGRESS:"MAT_CAT_TYPE.UPDATE_MAT_CATEGORY_PROGRESS",
    UPDATE_MAT_CATEGORY_SUCCESS:"MAT_CAT_TYPE.UPDATE_MAT_CATEGORY_SUCCESS",
    UPDATE_MAT_CATEGORY_ERROR:"MAT_CAT_TYPE.UPDATE_MAT_CATEGORY_ERROR",
    UPDATE_MAT_CATEGORY_RESET:"MAT_CAT_TYPE.UPDATE_MAT_CATEGORY_RESET",

}
export default MaterialCatTypes