const AddressTypes ={
    CREATE_BILLING_ADDRESS_PROGRESS:"ADDRESS_TYPE.CREATE_BILLING_ADDRESS_PROGRESS",
    CREATE_BILLING_ADDRESS_SUCCESS:"ADDRESS_TYPE.CREATE_BILLING_ADDRESS_SUCCESS",
    CREATE_BILLING_ADDRESS_ERROR:"ADDRESS_TYPE.CREATE_BILLING_ADDRESS_ERROR",
    CREATE_BILLING_ADDRESS_RESET:"ADDRESS_TYPE.CREATE_BILLING_ADDRESS_RESET",

    GET_BILLING_ADDRESS_PROGRESS:"ADDRESS_TYPE.GET_BILLING_ADDRESS_PROGRESS",
    GET_BILLING_ADDRESS_SUCCESS:"ADDRESS_TYPE.GET_BILLING_ADDRESS_SUCCESS",
    GET_BILLING_ADDRESS_ERROR:"ADDRESS_TYPE.GET_BILLING_ADDRESS_ERROR",

    UPDATE_BILLING_ADDRESS_PROGRESS:"ADDRESS_TYPE.UPDATE_BILLING_ADDRESS_PROGRESS",
    UPDATE_BILLING_ADDRESS_SUCCESS:"ADDRESS_TYPE.UPDATE_BILLING_ADDRESS_SUCCESS",
    UPDATE_BILLING_ADDRESS_ERROR:"ADDRESS_TYPE.UPDATE_BILLING_ADDRESS_ERROR",
    UPDATE_BILLING_ADDRESS_RESET:"ADDRESS_TYPE.UPDATE_BILLING_ADDRESS_RESET",



    CREATE_SHIPPING_ADDRESS_PROGRESS:"ADDRESS_TYPE.CREATE_SHIPPING_ADDRESS_PROGRESS",
    CREATE_SHIPPING_ADDRESS_SUCCESS:"ADDRESS_TYPE.CREATE_SHIPPING_ADDRESS_SUCCESS",
    CREATE_SHIPPING_ADDRESS_ERROR:"ADDRESS_TYPE.CREATE_SHIPPING_ADDRESS_ERROR",
    CREATE_SHIPPING_ADDRESS_RESET:"ADDRESS_TYPE.CREATE_SHIPPING_ADDRESS_RESET",

    GET_SHIPPING_ADDRESS_PROGRESS:"ADDRESS_TYPE.GET_SHIPPING_ADDRESS_PROGRESS",
    GET_SHIPPING_ADDRESS_SUCCESS:"ADDRESS_TYPE.GET_SHIPPING_ADDRESS_SUCCESS",
    GET_SHIPPING_ADDRESS_ERROR:"ADDRESS_TYPE.GET_SHIPPING_ADDRESS_ERROR",

    UPDATE_SHIPPING_ADDRESS_PROGRESS:"ADDRESS_TYPE.UPDATE_SHIPPING_ADDRESS_PROGRESS",
    UPDATE_SHIPPING_ADDRESS_SUCCESS:"ADDRESS_TYPE.UPDATE_SHIPPING_ADDRESS_SUCCESS",
    UPDATE_SHIPPING_ADDRESS_ERROR:"ADDRESS_TYPE.UPDATE_SHIPPING_ADDRESS_ERROR",
    UPDATE_SHIPPING_ADDRESS_RESET:"ADDRESS_TYPE.UPDATE_SHIPPING_ADDRESS_RESET",

}
export default AddressTypes